from pydantic import BaseModel, Field


class MemoDraft(BaseModel):
    """Raw output of write_memo(). Each field is the full text of one case,
    containing inline citation markers in the form <<N>>, where N is the
    1-based position of a claim in the claims list the model was given.

    These markers are NOT resolved here - render_citations() (M-03) turns
    them into renumbered [k] footnotes with a Sources section. Keeping the
    two steps separate means write_memo can be retried/regenerated by the
    evaluator (E-01/E-02) without re-running citation rendering, and
    render_citations can be unit tested with zero model calls.
    """

    bull_case: str = Field(..., description="Full text of the bull case, with inline <<N>> markers.")
    base_case: str = Field(..., description="Full text of the base case, with inline <<N>> markers.")
    bear_case: str = Field(..., description="Full text of the bear case, with inline <<N>> markers.")
